### ISSUE TITLE
古いリンクから yude.jp に飛んだときに画像が壊れる

### ISSUE THREAD

**Issue by KusaReMKN** [yudejp/yude.jp_v6#4]
例えば yude.jp の古いバージョンのページを指している URL `https://www.yude.jp/hoge/hoge/page` があって、これにアクセスすると `https://www.yude.jp/` と同様のページを表示しようとしますが、画像のパスが相対で指定されているためにページが壊れます。
親切であるならばリダイレクトを利用して `/` に飛ばすべきだと思います。あるいは、画像のパスを `/` 絶対で指定することで表示を修正できます。

**Comment by yude** [comment]
Fixed in 0a014a772732e36f2e1c23420361f48243d92409
